name: build
on: [push]
jobs:

  windows:
    name: Windows
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...
      
    - name: Embed
      run: |
        go get github.com/GeertJohan/go.rice
        go get github.com/GeertJohan/go.rice/rice
        go generate

    - name: Build
      run: go build -o builds/ReforgedLauncher.exe

    - uses: actions/upload-artifact@master
      with:
        name: windows
        path: builds
